-- Wilcke Worte teilt sich die Supabase-Datenbank mit wilckeweb.
-- Alle Tabellen sind daher mit "worte_" praefixiert.

create table if not exists public.worte_bookings (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('paket', 'projekt', 'equipment', 'kontakt')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  name text not null,
  email text not null,
  phone text,
  company text,
  details jsonb not null default '{}'::jsonb,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.worte_equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  preis_tag integer,
  image_url text,
  category text not null default 'Sonstiges',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists worte_bookings_created_at_idx on public.worte_bookings (created_at desc);
create index if not exists worte_bookings_status_idx on public.worte_bookings (status);
create index if not exists worte_equipment_sort_order_idx on public.worte_equipment (sort_order, id);

alter table public.worte_bookings enable row level security;
alter table public.worte_equipment enable row level security;

-- Der Next.js-Server nutzt SUPABASE_SERVICE_ROLE_KEY und umgeht damit RLS.
-- Es ist kein anonymer Tabellenzugriff vorgesehen; RLS verweigert alles Andere.
